## Quiz - sol

In [1]:
import numpy as np
import random

### 1. 5개의 1로 이루어진 정수데이터 타입의 벡터를 만드세요

In [2]:
np.ones(5) ;   # 놉

In [3]:
data = np.ones(5, dtype = 'int'); data

array([1, 1, 1, 1, 1])

### 2. 10개의 1로 이루어진 정수 데이터 타입의 벡터에서 마지막 3개의 데이터는 5가 들어있는 벡터를 만드세요

In [4]:
data = np.ones(10, dtype = 'int')
data[7:] = 5
data

array([1, 1, 1, 1, 1, 1, 1, 5, 5, 5])

In [5]:
data = np.ones(10, dtype = 'int')
data[-3:] = 5
data

array([1, 1, 1, 1, 1, 1, 1, 5, 5, 5])

### 3. 10에서 20까지의 데이터를 가지는 벡터를 만드세요

In [6]:
data = np.arange(10,21, dtype = 'int')
data

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

### 4. 위 벡터의 순서를 바꾸세요

In [7]:
data = np.arange(20,9,-1)
data

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [8]:
_[::-1]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

### 5. 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요

In [9]:
data = np.arange(9).reshape(3,3)
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 6. 위의 벡터에서  `[[4,5],[7,8]]`  행렬을 만드세요

In [10]:
data[1:,1:]

array([[4, 5],
       [7, 8]])

### 7. 1에서 10까지의 데이터를 랜덤하게 가지는 3*4 행렬을 만드세요

In [11]:
data = np.random.randint(1,11,size=12).reshape(3,4)
data

array([[1, 2, 6, 7],
       [2, 8, 5, 8],
       [3, 5, 1, 5]])

### 8. 위에서 만든 행렬의 unique 한 숫자들 리스트와 각숫자의 갯수를 리스트로 나타내세요

In [12]:
index, count = np.unique(data, return_counts = True)
print(index)
print(count)

[1 2 3 5 6 7 8]
[2 2 1 3 1 1 2]


### 9. 1에서 12까지에 숫자가 들어간 3*4 행렬을 만드시고 행과 열에 관계없이 데이터를 섞으세요

In [13]:
data = np.random.randint(1,13, size = 12).reshape(3,4)
np.random.shuffle(data)
data

array([[ 1,  8, 12,  4],
       [ 5,  7,  8,  2],
       [10,  2, 10,  3]])

In [14]:
data = data.reshape(12)
np.random.shuffle(data)
data.reshape(3,4)

array([[ 5,  8,  1,  4],
       [ 7,  2,  2,  3],
       [ 8, 10, 10, 12]])

### 10. 1부터 10까지의 랜덤한 데이터가 들어가는 `3*3`행렬을 만드시고 가장 아래에 위의 데이터를 모두 합한 `1*3`행렬을 추가해서 `4*3`행렬을 만드세요

In [48]:
data = np.random.randint(1,11,size = 9).reshape(3,3)
data

array([[10,  1,  1],
       [10,  1,  8],
       [ 5,  4,  8]])

In [49]:
# data = data[0] + data[1] + data[2]
data2 = data[0] + data[1] + data[2]
data2 = data2.reshape(1,3)

result = np.concatenate([data,data2], axis = 0)
result

array([[10,  1,  1],
       [10,  1,  8],
       [ 5,  4,  8],
       [25,  6, 17]])

In [50]:
sum_data = np.sum(data, axis = 0).reshape(1,3)
data = np.concatenate( [data, sum_data])
data

array([[10,  1,  1],
       [10,  1,  8],
       [ 5,  4,  8],
       [25,  6, 17]])

### 11. 10번문제의 결과로 나온 행렬데이터에서 평균값을 출력하고 평균값보다 큰 숫자들만 유니크한 리스트로 나열하세요 (평균값은 소수 둘째 자리까지만 나타내세요)

In [58]:
avg = result.mean()
print("avg : {}".format(avg))
result = result[result > avg]
np.unique(result)

avg : 15.5


array([17, 25])

In [59]:
avg_data = data.mean()
data = data[data > avg_data]
print("avg : ", round(avg_data, 2))
np.unique(data)

avg :  15.5


array([17, 25])

### 12. 1부터 20까지의 랜덤숫자를 가지는 5*5 행렬을 만드시고 최대값에는 숫자(MAX), 최소값에는 숫자(MIN)으로 행렬을 바꾸세요

In [20]:
mat = np.random.randint(1,21, size = 25).reshape(5,5);mat

array([[ 6,  4,  6,  1, 19],
       [17, 17,  6, 20,  9],
       [ 1, 18, 18,  6, 12],
       [ 7, 10, 13, 15,  8],
       [ 1, 13,  5, 18, 19]])

In [21]:
tmp_mat = []
for i in mat:
    for j in range(5):
        if i[j] == mat.max():
            tmp_mat.append("{}({})".format(i[j],"MAX"))
        elif i[j] == mat.min():
            tmp_mat.append("{}({})".format(i[j],"MIN"))
        else:
            tmp_mat.append(i[j])

In [22]:
result = np.array(tmp_mat); result.reshape(5,5)

array([['6', '4', '6', '1(MIN)', '19'],
       ['17', '17', '6', '20(MAX)', '9'],
       ['1(MIN)', '18', '18', '6', '12'],
       ['7', '10', '13', '15', '8'],
       ['1(MIN)', '13', '5', '18', '19']],
      dtype='<U21')

In [63]:
data = np.random.randint(1,21,size = (5,5))
data

array([[11, 19, 13,  4, 10],
       [16,  6, 15, 11,  8],
       [ 5, 10, 12,  9, 19],
       [13,  3, 14, 17, 10],
       [ 3,  6,  6, 19, 18]])

In [65]:
min_number, max_number = np.min(data), np.max(data)
min_number, max_number

(3, 19)

In [66]:
min_number, max_number = np.min(data), np.max(data)
min_idx = data == min_number
max_idx = data == max_number

In [67]:
data = data.astype('str')
data[min_idx] = str(min_number) + "(MIN)"
data[max_idx] = str(max_number) + "(MAX)"
data

array([['11', '19(MAX)', '13', '4', '10'],
       ['16', '6', '15', '11', '8'],
       ['5', '10', '12', '9', '19(MAX)'],
       ['13', '3(MIN)', '14', '17', '10'],
       ['3(MIN)', '6', '6', '19(MAX)', '18']],
      dtype='<U21')

### 13. 100에서 130까지의 랜덤 숫자를 가지는 8*8행렬을 만드시고 3의 배수에는 fiz, 5의 배수에는 buz, 3과 5의 배수는 fbz 문자를 출력하세요

In [25]:
mat = np.random.randint(100,131, size = 64).reshape(8,8);mat

array([[106, 125, 108, 117, 122, 130, 125, 115],
       [101, 127, 110, 118, 101, 125, 115, 112],
       [102, 119, 101, 113, 102, 109, 113, 128],
       [114, 105, 127, 117, 108, 121, 119, 124],
       [102, 105, 117, 120, 107, 122, 127, 104],
       [112, 112, 114, 121, 111, 109, 110, 106],
       [122, 101, 108, 100, 102, 106, 110, 110],
       [130, 111, 127, 102, 109, 126, 106, 115]])

In [26]:
tmp = []
for i in mat:
    for j in range(8):
        if i[j] % 3 == 0 and i[j] % 5 == 0:
            tmp.append("fbz")
        elif i[j] % 3 == 0:
            tmp.append("fiz")
        elif i[j] % 5 == 0:
            tmp.append("buz")
        else:
            tmp.append(str(i[j]))
mat_1 = np.array(tmp).reshape(8,8)
mat_1

array([['106', 'buz', 'fiz', 'fiz', '122', 'buz', 'buz', 'buz'],
       ['101', '127', 'buz', '118', '101', 'buz', 'buz', '112'],
       ['fiz', '119', '101', '113', 'fiz', '109', '113', '128'],
       ['fiz', 'fbz', '127', 'fiz', 'fiz', '121', '119', '124'],
       ['fiz', 'fbz', 'fiz', 'fbz', '107', '122', '127', '104'],
       ['112', '112', 'fiz', '121', 'fiz', '109', 'buz', '106'],
       ['122', '101', 'fiz', 'buz', 'fiz', '106', 'buz', 'buz'],
       ['buz', 'fiz', '127', 'fiz', '109', 'fiz', '106', 'buz']],
      dtype='<U3')

In [69]:
data = np.random.randint(100, 121, size = (8,8))
data

array([[107, 101, 101, 114, 116, 116, 103, 109],
       [119, 110, 109, 111, 118, 102, 119, 102],
       [102, 101, 107, 107, 101, 115, 102, 106],
       [116, 109, 108, 103, 113, 101, 104, 113],
       [120, 115, 110, 112, 102, 107, 120, 112],
       [116, 106, 119, 118, 102, 116, 117, 104],
       [111, 100, 101, 117, 113, 112, 101, 110],
       [109, 120, 104, 108, 102, 105, 105, 114]])

In [70]:
idx_3 = mat % 3 == 0
idx_5 = mat % 5 == 0
idx_15 = mat % 15 == 0

In [71]:
data = data.astype("str")
data[idx_3] = "fiz"
data[idx_5] = "buz"
data[idx_15] = "fbz"
data

array([['107', 'buz', 'fiz', 'fiz', '116', 'buz', 'buz', 'buz'],
       ['119', '110', 'buz', '111', '118', 'buz', 'buz', '102'],
       ['fiz', '101', '107', '107', 'fiz', '115', '102', '106'],
       ['fiz', 'fbz', '108', 'fiz', 'fiz', '101', '104', '113'],
       ['fiz', 'fbz', 'fiz', 'fbz', '102', '107', '120', '112'],
       ['116', '106', 'fiz', '118', 'fiz', '116', 'buz', '104'],
       ['111', '100', 'fiz', 'buz', 'fiz', '112', 'buz', 'buz'],
       ['buz', 'fiz', '104', 'fiz', '102', 'fiz', '105', 'buz']],
      dtype='<U21')

### 14. 리스트 컴프리헨션을 이용하여 아래와 같은 규칙은 갖는 행렬을 만드세요

In [72]:
number = int(input("number :"))
data = np.arange(1,number+1);data
result = np.stack([data*i for i in range(1,number+1)], axis =0)
print(result)

number :5
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


In [76]:
number = 5
data = np.array([[ i * j for j in range(1, number + 1)] for i in range(1, number + 1)])
print("number : ", number)
data

number :  5


array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])