## Quiz - sol

In [2]:
import numpy as np

### 1. 5개의 1로 이루어진 정수데이터 타입의 벡터를 만드세요

In [6]:
np.ones(5) ; o  # 놉

array([ 1.,  1.,  1.,  1.,  1.])

In [8]:
data = np.ones(5, dtype = 'int'); data

array([1, 1, 1, 1, 1])

### 2. 10개의 1로 이루어진 정수 데이터 타입의 벡터에서 마지막 3개의 데이터는 5가 들어있는 벡터를 만드세요

In [13]:
data = np.ones(10, dtype = 'int')
data[7:] = 5
data

array([1, 1, 1, 1, 1, 1, 1, 5, 5, 5])

### 3. 10에서 20까지의 데이터를 가지는 벡터를 만드세요

In [4]:
data = np.arange(10,21, dtype = 'int')
data

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

### 4. 위 벡터의 순서를 바꾸세요

In [14]:
data = np.arange(20,9,-1)
data

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

### 5. 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요

In [18]:
data = np.arange(9).reshape(3,3)
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 6. 위의 벡터에서  `[[4,5],[7,8]]`  행렬을 만드세요

In [25]:
data[1:,1:]

array([[4, 5],
       [7, 8]])

### 7. 1에서 10까지의 데이터를 랜덤하게 가지는 3*4 행렬을 만드세요

In [26]:
data = np.random.randint(1,10,size=12).reshape(3,4)
data

array([[4, 3, 7, 7],
       [4, 3, 9, 8],
       [1, 1, 2, 7]])

### 8. 위에서 만든 행렬의 unique 한 숫자들 리스트와 각숫자의 갯수를 리스트로 나타내세요

In [34]:
index, count = np.unique(data, return_counts = True)print(index)
print(count)

[1 2 3 4 7 8 9]
[2 1 2 2 3 1 1]


### 9. 1에서 12까지에 숫자가 들어간 3*4 행렬을 만드시고 행과 열에 관계없이 데이터를 섞으세요

In [49]:
data = np.random.randint(1,13, size = 12).reshape(3,4)
np.random.shuffle(data)
data

array([[ 5,  2, 11,  7],
       [ 2, 11, 10, 10],
       [10,  2,  7,  9]])

### 10. 1부터 10까지의 랜덤한 데이터가 들어가는 `3*3`행렬을 만드시고 가장 아래에 위의 데이터를 모두 합한 `1*3`행렬을 추가해서 `4*3`행렬을 만드세요

In [76]:
data = np.random.randint(1,11,size = 9).reshape(3,3)
data

array([[9, 7, 3],
       [3, 5, 5],
       [7, 7, 4]])

In [98]:
# data = data[0] + data[1] + data[2]
data2 = data[0] + data[1] + data[2]
data2 = data2.reshape(1,3)

result = np.concatenate([data,data2], axis = 0)
result

array([[ 9,  7,  3],
       [ 3,  5,  5],
       [ 7,  7,  4],
       [19, 19, 12]])

### 11. 10번문제의 결과로 나온 행렬데이터에서 평균값을 출력하고 평균값보다 큰 숫자들만 유니크한 리스트로 나열하세요 (평균값은 소수 둘째 자리까지만 나타내세요)

In [115]:
avg = result.mean()
print("avg : {}".format(avg))
# np.unique(result > avg)
print(result[result > avg] )

avg : 8.333333333333334
[ 9 19 19 12]


### 12. 1부터 20까지의 랜덤숫자를 가지는 5*5 행렬을 만드시고 최대값에는 숫자(MAX), 최소값에는 숫자(MIN)으로 행렬을 바꾸세요

In [3]:
mat = np.random.randint(1,21, size = 25).reshape(5,5);mat

array([[ 8, 11,  6, 19, 16],
       [ 2,  6, 14, 11,  9],
       [ 7,  5, 18,  7, 20],
       [ 4,  8, 19, 17, 12],
       [10,  8, 14, 18, 15]])

In [22]:
tmp_mat = []
for i in mat:
    for j in range(5):
        if i[j] == mat.max():
            tmp_mat.append("{}({})".format(i[j],"MAX"))
        elif i[j] == mat.min():
            tmp_mat.append("{}({})".format(i[j],"MIN"))
        else:
            tmp_mat.append(i[j])

In [29]:
result = np.array(tmp_mat); result.reshape(5,5)

array([['8', '11', '6', '19', '16'],
       ['2(MIN)', '6', '14', '11', '9'],
       ['7', '5', '18', '7', '20(MAX)'],
       ['4', '8', '19', '17', '12'],
       ['10', '8', '14', '18', '15']],
      dtype='<U21')

### 13. 100에서 130까지의 랜덤 숫자를 가지는 8*8행렬을 만드시고 3의 배수에는 fiz, 5의 배수에는 buz, 3과 5의 배수는 fbz 문자를 출력하세요

In [30]:
mat = np.random.randint(100,131, size = 64).reshape(8,8);mat

array([[102, 108, 102, 102, 123, 117, 111, 129],
       [120, 108, 124, 108, 108, 130, 115, 113],
       [106, 121, 115, 126, 113, 125, 111, 129],
       [112, 100, 119, 122, 118, 115, 107, 103],
       [128, 113, 116, 127, 102, 104, 127, 115],
       [129, 129, 122, 111, 122, 116, 107, 124],
       [105, 121, 127, 109, 126, 119, 103, 106],
       [112, 125, 129, 108, 106, 100, 113, 114]])

In [44]:
tmp = []
for i in mat:
    for j in range(8):
        if i[j] % 3 == 0 and i[j] % 5 == 0:
            tmp.append("fbz")
        elif i[j] % 3 == 0:
            tmp.append("fiz")
        elif i[j] % 5 == 0:
            tmp.append("buz")
        else:
            tmp.append(str(i[j]))
mat_1 = np.array(tmp).reshape(8,8)
mat_1

array([['fiz', 'fiz', 'fiz', 'fiz', 'fiz', 'fiz', 'fiz', 'fiz'],
       ['fbz', 'fiz', '124', 'fiz', 'fiz', 'buz', 'buz', '113'],
       ['106', '121', 'buz', 'fiz', '113', 'buz', 'fiz', 'fiz'],
       ['112', 'buz', '119', '122', '118', 'buz', '107', '103'],
       ['128', '113', '116', '127', 'fiz', '104', '127', 'buz'],
       ['fiz', 'fiz', '122', 'fiz', '122', '116', '107', '124'],
       ['fbz', '121', '127', '109', 'fiz', '119', '103', '106'],
       ['112', 'buz', 'fiz', 'fiz', '106', 'buz', '113', 'fiz']],
      dtype='<U3')

### 14. 리스트 컴프리헨션을 이용하여 아래와 같은 규칙은 갖는 행렬을 만드세요

In [149]:
number = int(input("number :"))
data = np.arange(1,number+1);data
result = np.stack([data*i for i in range(1,number+1)], axis =0)
print(result)

number :7
[[ 1  2  3  4  5  6  7]
 [ 2  4  6  8 10 12 14]
 [ 3  6  9 12 15 18 21]
 [ 4  8 12 16 20 24 28]
 [ 5 10 15 20 25 30 35]
 [ 6 12 18 24 30 36 42]
 [ 7 14 21 28 35 42 49]]
