## Calculate
- basic calculate
- broadcasting
- functions
- performance

In [1]:
import numpy as np

### basic calculate

In [2]:
# list ( ls *= 3 )
ls = [1,2,3,4,5]
print("before : {}".format(ls))
for idx in range(len(ls)):
    ls[idx] = ls[idx] * 3
print("after : {}".format(ls))

before : [1, 2, 3, 4, 5]
after : [3, 6, 9, 12, 15]


In [3]:
# np.array ( na *= 3 )
na = np.array(ls)
na *= 3
print(type(na), na)

<class 'numpy.ndarray'> [ 9 18 27 36 45]


In [4]:
na_2 = np.array([6,7,8,9,10])  # 데이터의 개수를 맞춰서 계산
result = na * na_2
print("{}\n{}\n{}".format(na, na_2, result))

[ 9 18 27 36 45]
[ 6  7  8  9 10]
[ 54 126 216 324 450]


In [13]:
# 9와 같으면 True, 30보다 크면 True
na == 9, na > 30

(array([ True, False, False, False, False]),
 array([False, False, False,  True,  True]))

In [5]:
# 3의 배수이면 True
idx = na_2 % 3 == 0
print(idx)

[ True False False  True False]


In [6]:
# 3의 배수만 남기기 - Ture, False 리스트를 offset으로 넣어주면 True인 데이터만 남는다.
print(na_2)
print(na_2[idx])

[ 6  7  8  9 10]
[6 9]


In [7]:
# 리스트에서 같은 수 추출하기
na1 = np.array([1,2,3,4,5])
na2 = np.array([1,3,3,4,4])
print(na1 == na2)
print(na1[na1 == na2])

[ True False  True  True False]
[1 3 4]


In [8]:
# 리스트에서 비교연산으로 수 추출하기
na1 = np.array([1,2,3,4,5])
na2 = np.array([1,3,3,4,4])
print(na1 >= na2)
print(na1[na1 >= na2])

[ True False  True  True  True]
[1 3 4 5]


In [9]:
# 전체 리스트 비교하기
na1 = np.array([1,2,3,4,5])
na2 = np.array([1,3,3,4,4])
na3 = np.array([1,2,3,4,5])
print(np.all(na1 == na2))
print(np.all(na1 == na3))

False
True


In [10]:
# 스칼라, 벡터, 행렬 각 요소 곱셈
na = np.arange(6)
na2 = np.arange(6,12)

print("array1 : {}".format(na))
print("array2 : {}".format(na2))

print("scala : {}".format(na * 10))
print("vector : {}".format(na * na2))

array1 : [0 1 2 3 4 5]
array2 : [ 6  7  8  9 10 11]
scala : [ 0 10 20 30 40 50]
vector : [ 0  7 16 27 40 55]
array3 : 
[[0 1 2]
 [3 4 5]]
array4 : 
[[ 6  7  8]
 [ 9 10 11]]
matrix : 
[[ 0  7 16]
 [27 40 55]]


In [11]:
na3 = na.reshape(2,3)
na4 = na2.reshape(2,3)
print("array3 : \n{}".format(na3))
print("array4 : \n{}".format(na4))
print("matrix : \n{}".format(na3 * na4))

array3 : 
[[0 1 2]
 [3 4 5]]
array4 : 
[[ 6  7  8]
 [ 9 10 11]]
matrix : 
[[ 0  7 16]
 [27 40 55]]


### broadcasting

In [12]:
# broadcating exam 1  
na1 = np.arange(12)
na2 = na1.reshape(3,4)
print("na1 : \n{}".format(na1))
print("na2 : \n{}".format(na2))

na3 = np.ones_like(na1)
na3 = na3.reshape(3,4)
print("na3 : \n{}".format(na3))

na1 : 
[ 0  1  2  3  4  5  6  7  8  9 10 11]
na2 : 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
na3 : 
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [13]:
# + 1 만해도 행렬의 모든 요소에 1을 다 더한다. (broadcating 개념)
print("na2 + 1 : \n{}".format(na2 + 1)) 
print("na2 + na3 : \n{}".format(na2 + na3))

na2 + 1 : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
na2 + na3 : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
# broadcating exam 2
na4 = np.arange(4)
print("na2 : \n{}".format(na2))
print("na4 : \n{}".format(na4))

print("na2 + na4 : \n{}".format(na2 + na4)) # 모든 행에 n4를 다 더한다.

na5 = np.stack((na4, na4, na4))
print("na5 : \n{}".format(na5))

print("na2 + na5 : \n{}".format(na2 + na5))

na2 : 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
na4 : 
[0 1 2 3]
na2 + na4 : 
[[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]]
na5 : 
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
na2 + na5 : 
[[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]]


In [16]:
# broadcating exam 3

na6 = np.arange(3)[:,np.newaxis]
print("na2 : \n{}".format(na2))
print("na6 : \n{}".format(na6))

print("na2 + na6 : \n{}".format(na2 + na6)) # 모든 열에 na6를 다 더한다. 

na7 = np.array([[ i for _ in range(4)] for i in range(3)])  # 컴프리핸션 안에 컴프리핸션을 넣은 경우
print("na7 : \n{}".format(na7))

print("na2 + na7 : \n{}".format(na2 + na7))

na2 : 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
na6 : 
[[0]
 [1]
 [2]]
na2 + na6 : 
[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]]
na7 : 
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]]
na2 + na7 : 
[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]]


### functions
- min, max, argmin, argmax
- sum, mean, median, std, var
- all, any
- quartile
- exp, log

In [18]:
r = np.random.rand(2,3)
r_num = np.arange(5)
r_num = (r*10).astype('int64')
print("random matrix : \n{}".format(r_num))
print("min : {}".format(r_num.min()))
print("max : {}".format(r_num.max()))
print("argmin : {}".format(r_num.argmin())) # 최소값 위치
print("argmax : {}".format(r_num.argmax())) # 최대값 위치
print("mean : {}".format(r_num.mean()))

random matrix : 
[[0 1 1]
 [7 9 5]]
min : 0
max : 9
argmin : 0
argmax : 4
mean : 3.8333333333333335


In [19]:
r = np.random.rand(2,3)
r_num = np.arange(5)
r_num = (r*10).astype('int64')
print("random matrix : \n{}".format(r_num))
print("sum : {}".format(np.sum(r_num)))
print("sum_axis_0 : {}".format(np.sum(r_num, axis=0)))
print("sum_axis_1 : {}".format(np.sum(r_num, axis=1)))
print("median : {}".format(np.median(r_num))) # 중앙값
print("std : {}".format(np.std(r_num))) # standard deviation (표준편차)
print("var : {}".format(np.var(r_num))) # variance (변화량)

random matrix : 
[[6 4 9]
 [2 7 3]]
sum : 31
sum_axis_0 : [ 8 11 12]
sum_axis_1 : [19 12]
median : 5.0
std : 2.4094720491334933
var : 5.805555555555556


In [20]:
# all
# 모든 요소의 조건이 충족하면 True
n1 = np.array(range(3,8))
n2 = n1
n3 = np.array(range(1,11,2))

print(n1, n2, n3, end="\n\n")

print(n1 ==  n2)
print(np.all(n1 ==  n2))
print(n1 ==  n3)
print(np.all(n1 ==  n3))
print(n1 >  n3)
print(np.all(n1 >  n3))

[3 4 5 6 7] [3 4 5 6 7] [1 3 5 7 9]

[ True  True  True  True  True]
True
[False False  True False False]
False
[ True  True False False False]
False


In [21]:
# any
# 요소의 하나라도 조건이 충족하면 True
n1 = np.array(range(3,8))
n2 = n1
n3 = np.array(range(1,11,2))

print(n1, n2, n3, end="\n\n")

print(n1 ==  n2)
print(np.any(n1 ==  n2))
print(n1 ==  n3)
print(np.any(n1 ==  n3))
print(n1 >  n3)
print(np.any(n1 >  n3))

[3 4 5 6 7] [3 4 5 6 7] [1 3 5 7 9]

[ True  True  True  True  True]
True
[False False  True False False]
True
[ True  True False False False]
True


In [22]:
# quartile (사분위수)
na = np.array([num for num in range(0,101)])
print(na)
np.percentile(na, 25), np.percentile(na, 45)  # 25퍼센트에 해당되는 데이터가 나오는 것

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]


(25.0, 45.0)

In [23]:
# quartile (사분위수)
na = np.array([num for num in range(0,51)])
print(na)
np.percentile(na, 25), np.percentile(na, 45)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50]


(12.5, 22.5)

In [24]:
# exponential function (지수함수)
na = np.arange(1,6)
print(na)
print(np.exp(na))

# 차이는 1씩 밖에 안나지만 지수함수를 씌워주면 확대된 걸로 볼 수 있다. 

[1 2 3 4 5]
[   2.71828183    7.3890561    20.08553692   54.59815003  148.4131591 ]


In [25]:
# log function (로그함수)
na = np.arange(1,6)
print(na)
print(np.log(na))

# 수치들이 너무 커서 좀 축소해서 보고 싶을 때

[1 2 3 4 5]
[ 0.          0.69314718  1.09861229  1.38629436  1.60943791]


### performance
- 10**7개의 리스트에서 3과 5의 배수의 갯수를 찾는 시간

In [26]:
ls = []
size = int(1E7)
for data in range(size):
    ls.append(data)
na = np.array(ls)

In [32]:
# for문을 이용해서

%time
count = 0
for idx in range(len(ls)):
    if (ls[idx] % 3 == 0) or (ls[idx] % 5 == 0):
        count += 1
print(count)

CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 8.11 µs
4666667


In [33]:
# numpy를 이용해서

%time
count = len(na[(na%3 == 0) | (na%5 == 0)])
print(count)

CPU times: user 3 µs, sys: 1e+03 ns, total: 4 µs
Wall time: 7.87 µs
4666667
