## Datatype
- boolean : bool
- integer : int64
- float : float64
- byte String : S24
- unicode String : U24

In [1]:
import numpy as np

In [2]:
na = np.array([True, False])
na.dtype

dtype('bool')

In [3]:
na = np.array([1, 2, 3])
na.dtype # 안에 들어있는 value값들에 대한 타입은 동일하다

dtype('int64')

In [4]:
na = np.array([1.0, 2.0, 3.0])
na.dtype

dtype('float64')

### change datatype

In [7]:
na = np.array([-1.0, 0.0, 1.0, 2.2, 3.8])
print(na)

na = na.astype('int64')
print(na)

na = na.astype('bool')
print(na)

na = na.astype('S24')  # byte string
print(na)

na = na.astype('U24')  # boolean string
print(na)

[-1.   0.   1.   2.2  3.8]
[-1  0  1  2  3]
[ True False  True  True  True]
[b'True' b'False' b'True' b'True' b'True']
['True' 'False' 'True' 'True' 'True']


In [10]:
# 5~10까지 랜덤한 숫자가 들어있는 5*5 행렬
na = np.random.rand(5,5)
print(na)

[[ 0.24421475  0.56224048  0.36370236  0.88340208  0.23399941]
 [ 0.88868741  0.45219839  0.12702293  0.29601854  0.45143228]
 [ 0.26289102  0.20460083  0.10230756  0.97367455  0.18419175]
 [ 0.26094035  0.45999007  0.60375228  0.54093418  0.89407241]
 [ 0.59608952  0.65862243  0.54742561  0.00289919  0.20450173]]


In [11]:
na * 6 + 5  

array([[  6.46528849,   8.37344286,   7.18221417,  10.30041249,
          6.40399645],
       [ 10.33212447,   7.71319036,   5.76213757,   6.77611123,   7.7085937 ],
       [  6.57734611,   6.22760496,   5.61384534,  10.84204733,
          6.10515052],
       [  6.56564211,   7.75994045,   8.62251369,   8.24560507,
         10.36443446],
       [  8.57653709,   8.95173458,   8.28455368,   5.01739514,
          6.22701035]])

In [12]:
na = (na*6+5).astype('int64')
print(na)

[[ 6  8  7 10  6]
 [10  7  5  6  7]
 [ 6  6  5 10  6]
 [ 6  7  8  8 10]
 [ 8  8  8  5  6]]
