### Reference
- http://www.numpy.org/
- http://aikorea.org/cs231n/python-numpy-tutorial/

### Install
- pip3 install numpy

## Make
- array
- reshape
- index
- zeros
- ones
- eye
- like
- empty
- arange
- linespace, logspace
- rand, randn
- stack
- concatenate
- split
- sort

In [1]:
import numpy as np

### array
- ndim : 행렬의 차원
- shape : 행렬의 모양

In [2]:
# 1차원 배열 (vector)
array = np.array([0,1,2,3,4,5])
print(type(array))
print(array)

# ndarray 형식은 콤마가 없다는 것을 유의하자

<class 'numpy.ndarray'>
[0 1 2 3 4 5]


In [3]:
# 2차원 배열 (1*3 matrix)
array = np.array([[0],[1],[2]]) 
print(array)

[[0]
 [1]
 [2]]


In [4]:
# 2차원 배열 (2*3 matrix)
array = np.array([
    [0,1,2],
    [3,4,5]
]) 
print(array)

[[0 1 2]
 [3 4 5]]


In [5]:
# 3차원 배열 (2*3*4 matrix)
array = np.array([
    [[0,1,2,3],
     [4,5,6,7],
     [8,9,10,11]],
    [[0,1,2,3],
     [4,5,100,7],
     [8,9,10,11]]
]) 
print(array)
print(array.ndim, array.shape) # 바깥에서 안으로 모양을 나타낸다고 생각하면 편함

# ndim => ndarray가 몇차원인지 알 수 있음

[[[  0   1   2   3]
  [  4   5   6   7]
  [  8   9  10  11]]

 [[  0   1   2   3]
  [  4   5 100   7]
  [  8   9  10  11]]]
3 (2, 3, 4)


### reshape
- 행렬의 모양을 바꿀수 있다.

In [6]:
na = np.array([1,2,3,4,5,6,7,8])
na

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
na = np.array([1,2,3,4,5,6,7,8])
na.reshape(2,4)   
# ndarray의 데이터의 숫자와 reshape() 안에 들어가는 숫자의 곱이 같아야 한다.

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
rna = np.reshape(na,(4,2))
rna

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [9]:
# 전치행렬
rna.T

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

### index
- 행렬의 특정 위치 데이터 값 가져오기
- 행렬 자르기

In [10]:
array

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[  0,   1,   2,   3],
        [  4,   5, 100,   7],
        [  8,   9,  10,  11]]])

In [11]:
print(array[1][1][2])  # 가장 바깥쪽부터 읽는다
print(array[1,1,2])

100
100


In [12]:
result = array[1:,1:,2:]    # 자른다고 생각하면 편하다
print(result)
print(result.ndim, result.shape)

[[[100   7]
  [ 10  11]]]
3 (1, 2, 2)


In [13]:
print(array[1])    # 차원이 축소된다.

[[  0   1   2   3]
 [  4   5 100   7]
 [  8   9  10  11]]


In [14]:
print(array[1:])   # 차원이 축소되지 않는다.

[[[  0   1   2   3]
  [  4   5 100   7]
  [  8   9  10  11]]]


In [15]:
# 차원을 줄이려면?
result[0][0]

array([100,   7])

### zeros
- 행렬을 만들고 안에 0으로 채워 넣는다.

In [16]:
# 1차원
z = np.zeros(5)
print(z)
print(z.ndim, z.shape)

[ 0.  0.  0.  0.  0.]
1 (5,)


In [17]:
# 2차원 (2*3)
z = np.zeros((2,3))
print(z)
print(z.ndim, z.shape)

[[ 0.  0.  0.]
 [ 0.  0.  0.]]
2 (2, 3)


In [18]:
# 3차원 (2*3*4)
z = np.zeros([2,3,4])
print(z)
print(z.ndim, z.shape)

[[[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]]
3 (2, 3, 4)


### ones
- 행렬을 만들고 안에 1을 채워 넣는다.

In [19]:
# 3차원 (2*3*4)
o = np.ones([2,3,4])
print(o)
print(o.ndim, o.shape)

[[[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]]
3 (2, 3, 4)


### eye
- 단위 행렬 데이터를 만든다.

In [20]:
# 단위행렬
np.eye(3)   # np.eye(2,3) 하면 에러뜸

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

### like
- 행렬 안에 있는 모든 데이터를 0이나 1로 바꿀수 있다.

In [21]:
z

array([[[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]])

In [22]:
ls = np.ones_like(z)
print(ls)
print(ls.ndim, ls.shape)

[[[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]]
3 (2, 3, 4)


In [23]:
o

array([[[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]])

In [24]:
ls = np.zeros_like(o)
print(ls)
print(ls.ndim, ls.shape)

[[[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]]
3 (2, 3, 4)


### empty
- 빈행렬을 만든다.
- 실제로는 빈데이터가 아니라 더미 데이터가 들어간다

In [25]:
a = np.empty((5,5))
print(a)

[[ -0.00000000e+000  -2.00389757e+000   2.15265879e-314   2.47032823e-323
    0.00000000e+000]
 [  0.00000000e+000   0.00000000e+000   1.69400391e-094   0.00000000e+000
    0.00000000e+000]
 [  2.86051697e-221   0.00000000e+000   0.00000000e+000  -9.46887150e-082
    0.00000000e+000]
 [  0.00000000e+000  -3.70814272e-237   0.00000000e+000   0.00000000e+000
   -2.84009250e+234]
 [  0.00000000e+000   0.00000000e+000   9.11851440e+224   0.00000000e+000
    0.00000000e+000]]


### arange
- range와 같다.
- 하지만 큰데이터에서 range 보다 속도가 빠르다

In [26]:
# range와 arange의 속도 비교
size = int(1E6) # E : exponential
%timeit for x in range(size): x ** 2
%timeit for x in np.arange(size): x ** 2

380 ms ± 12.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
284 ms ± 4.82 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [29]:
np.arange(2,10,3)

array([2, 5, 8])

In [30]:
np.arange(10,1,-2)

array([10,  8,  6,  4,  2])

### linspace, logspace

- 두 가지 방법으로도 numpy배열을 생성할 수 있다.

In [31]:
np.linspace(0, 100, 5)

array([   0.,   25.,   50.,   75.,  100.])

In [32]:
# log10(x)=2, log10(x)=2.5, log10(x)=3
# 10**2, 10**2.5, 10**3
print(np.logspace(2, 4, 3))
print(np.logspace(2, 3, 3))

[   100.   1000.  10000.]
[  100.           316.22776602  1000.        ]


In [33]:
10**2, 10**2.5, 10**3

(100, 316.22776601683796, 1000)

### random
- seed
- rand (uniform)
- randn (gaussian)
- randint
- shuffle
- choice

In [34]:
np.random.seed(0)
rd = np.random.rand(10)   # uniform 으로 난수 발생  (균등분포)
rdn = np.random.randn(10) # gaussian 으로 난수 발생 (정규분포 - 0에 가까운수가 많이 나옴)
print(rd)
print(rdn)

[ 0.5488135   0.71518937  0.60276338  0.54488318  0.4236548   0.64589411
  0.43758721  0.891773    0.96366276  0.38344152]
[ 0.14404357  1.45427351  0.76103773  0.12167502  0.44386323  0.33367433
  1.49407907 -0.20515826  0.3130677  -0.85409574]


In [35]:
np.random.seed(0)
rd = np.random.rand(10)   # uniform 으로 난수 발생  (균등분포)
rdn = np.random.randn(10) # gaussian 으로 난수 발생 (정규분포 - 0에 가까운수가 많이 나옴)
print(rd)
print(rdn)

# np.random.sedd(x)   seed 값이 같으면 같은 수가 뽑힘.
# random 모듈과는 다름

[ 0.5488135   0.71518937  0.60276338  0.54488318  0.4236548   0.64589411
  0.43758721  0.891773    0.96366276  0.38344152]
[ 0.14404357  1.45427351  0.76103773  0.12167502  0.44386323  0.33367433
  1.49407907 -0.20515826  0.3130677  -0.85409574]


In [36]:
# e-01 -> (10**-1)
np.random.seed(1)
rd = np.random.rand(4)
rdn = np.random.randn(4)
print(rd)
print(rdn)

[  4.17022005e-01   7.20324493e-01   1.14374817e-04   3.02332573e-01]
[-0.52817175 -1.07296862  0.86540763 -2.3015387 ]


In [37]:
r = np.random.rand(2,3,4)
print(r)

[[[ 0.41919451  0.6852195   0.20445225  0.87811744]
  [ 0.02738759  0.67046751  0.4173048   0.55868983]
  [ 0.14038694  0.19810149  0.80074457  0.96826158]]

 [[ 0.31342418  0.69232262  0.87638915  0.89460666]
  [ 0.08504421  0.03905478  0.16983042  0.8781425 ]
  [ 0.09834683  0.42110763  0.95788953  0.53316528]]]


In [38]:
r = np.random.randint(0,10,(3,3))  
print(r)
# (start, end, shape)  end 데이터는 나오지 않게 된다

[[4 8 1]
 [4 0 3]
 [9 2 0]]


In [39]:
r = np.random.randint(10, size=(3,3))
r

array([[4, 9, 2],
       [7, 7, 9],
       [8, 6, 9]])

In [40]:
r = np.random.randint(10, size=(3,4))
r

array([[3, 7, 7, 4],
       [5, 9, 3, 6],
       [8, 0, 2, 7]])

In [41]:
# shuffle로 데이터의 순서를 바꿀수 있다.  실행할때 마다 바뀜
np.random.shuffle(r)
r

array([[3, 7, 7, 4],
       [8, 0, 2, 7],
       [5, 9, 3, 6]])

In [42]:
# p의 확률로 range(5)를 10개 추출  
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0])  
# p의 확률로 데이터를 뽑는다  0이 나올 확률은 0.1, 1이 나올 확률은 0

array([2, 3, 3, 2, 3, 3, 3, 0, 3, 3])

In [43]:
# 유일한 값만 뽑아준다
np.unique(r)

array([0, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
# unique로 데이터의 유일한 값에 대한 리스트와 값의 갯수를 구할수 있다
index, count = np.unique(r, return_counts=True)   
index, count
# return_count keyword parameter
print(r)
print('--------------------')
print(index)
print(count)

[[1 9 8 2 3 1]
 [2 7 2 6 0 9]
 [2 6 6 2 7 7]
 [0 6 5 1 4 6]]
--------------------
[0 1 2 3 4 5 6 7 8 9]
[2 3 5 1 1 1 5 3 1 2]


### stack
- 행렬을 쌓는것과 같이 합치는 방법
- 축이 기준이 된다 (세로축 or 가로축)

- `hstack` : 행의 수가 같은 두 개 이상의 배열을 옆으로 연결하여 열의 수가 더 많은 배열을 만든다.
- `vstack` : 명령은 열의 수가 같은 두 개 이상의 배열을 위아래로 연결하여 행의 수가 더 많은 배열을 만든다.
- `dstack` : 명령은 제3의 축, 행이나 열이 아닌 깊이(depth) 방향으로 배열을 합친다. 
- `axis` : 인수 (디폴트 0)를 사용하여 연결후의 회전 방향을 정한다.
- `axis = 0` : 앞쪽에 차원이 삽입된다. 행을 쌓는다.
- `axis = 1` : 두번째에 차원이 삽입된다. 열을 쌓는다.

In [45]:
na1 = np.arange(6)
na2 = np.arange(6,12)
print(na1, na1.shape)
print(na2, na2.shape)

[0 1 2 3 4 5] (6,)
[ 6  7  8  9 10 11] (6,)


In [46]:
# 1 * 6의 벡터 형태의 데이터가 2 * 6 의 형태로 쌓였다. 수평으로 쌓였다
na3 = np.stack((na1, na2))
print(na3, na3.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] (2, 6)


In [47]:
# axis = 축  0 = 수직으로 쌓을 때 1 = 수직으로 쌓을때
na3 = np.stack((na1, na2), axis=1)
print(na3, na3.shape) 

[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]] (6, 2)


In [80]:
na3 = np.stack((na1, na2), axis=0)
print(na3)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [48]:
# practice 1
ls = []
for i in range(5):
    print(range(7), i, i+3)
    print(range(7)[i:i+3])
    print(list(range(7)[i:i+3]), end="\n\n")
    ls.append(range(7)[i:i+3])    
ls

range(0, 7) 0 3
range(0, 3)
[0, 1, 2]

range(0, 7) 1 4
range(1, 4)
[1, 2, 3]

range(0, 7) 2 5
range(2, 5)
[2, 3, 4]

range(0, 7) 3 6
range(3, 6)
[3, 4, 5]

range(0, 7) 4 7
range(4, 7)
[4, 5, 6]



[range(0, 3), range(1, 4), range(2, 5), range(3, 6), range(4, 7)]

In [79]:
# 수직으로 합치기
np.vstack(ls)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [50]:
# 수평으로 합치기. 하지만 리스트가 된다
np.hstack(ls)

array([0, 1, 2, 1, 2, 3, 2, 3, 4, 3, 4, 5, 4, 5, 6])

In [84]:
# 수평으로 합치기
data = [list(range(7)[i:i+3]) for i in range(5) ] 

print(data)
print(len(data))


[[0, 1, 2], [1, 2, 3], [2, 3, 4], [3, 4, 5], [4, 5, 6]]
5


In [52]:
# axis = -1 과 1 같습니다.
np.stack(data, axis=-1)

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [53]:
# practice 2
np.arange(5)[:, np.newaxis]
# 새로운 축이 생기는 것
# :  > 처음부터 끝까지 새로운 축을 만드는 것

array([[0],
       [1],
       [2],
       [3],
       [4]])

### concatenate (결합)
- 가로 결합은 열의 갯수가 같아야 한다.
- 세로 결합은 행의 갯수가 같아야 한다.
- 축이 아니라 하나의 데이터 매트릭스가 기준이라고 보면 된다. 

```
n1,n2
이거나

n1
n2
이렇게
```

In [54]:
r1 = np.random.randint(10, size=(2,3))
print(r1, r1.shape)

[[6 2 5]
 [7 8 4]] (2, 3)


In [55]:
r2 = np.random.randint(10, size=(3,2))
print(r2, r2.shape)

[[4 7]
 [7 4]
 [9 0]] (3, 2)


In [56]:
r3 = np.random.randint(10, size=(3,3))
print(r3, r3.shape)

[[2 0 7]
 [1 7 9]
 [8 4 0]] (3, 3)


In [57]:
# 가로 결합
np.concatenate([r1, r3], axis=0)  # 수직 결합이 가능해짐

array([[6, 2, 5],
       [7, 8, 4],
       [2, 0, 7],
       [1, 7, 9],
       [8, 4, 0]])

In [58]:
# 세로 결합
np.concatenate([r2, r3], axis=1)  # 수평 결합이 가능해짐

array([[4, 7, 2, 0, 7],
       [7, 4, 1, 7, 9],
       [9, 0, 8, 4, 0]])

### split

In [59]:
r = np.arange(0,10)
r

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
r1 = np.split(r, [5]) # 앞에서 5번째를 기준으로 나눈다
r1

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [61]:
# r1에는 나눈 데이터의 첫번째 데이터가 r2에는 나눈 데이터의 두번째 데이터가 들어간다
r1, r2 = np.split(r, [5]) 
r1, r2

(array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]))

In [62]:
# 2,4,6,8을 기준으로 나눠 5개의 array 데이터가 생성된다. index 값이라는 것을 기억하자
r1, r2, r3, r4, r5 = np.split(r, [2,4,6,8]) 
r1, r2, r3, r4, r5

(array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9]))

### vsplit/hsplit
- 행렬을 수직, 수평으로 나눈다

In [63]:
r = np.random.randint(10, size=(4,6))
r, r.shape

(array([[1, 9, 8, 2, 3, 1],
        [2, 7, 2, 6, 0, 9],
        [2, 6, 6, 2, 7, 7],
        [0, 6, 5, 1, 4, 6]]), (4, 6))

In [64]:
# 수직으로 2개씩 자름
r1, r2 = np.vsplit(r, [2])
print(r1, r1.shape)
print(r2, r2.shape)

[[1 9 8 2 3 1]
 [2 7 2 6 0 9]] (2, 6)
[[2 6 6 2 7 7]
 [0 6 5 1 4 6]] (2, 6)


In [65]:
# 수직으로 1행 자르고, 2행자르고, 그러고 나면 나머지 2개행  따라서 3개의 행렬이 생김
r1, r2, r3 = np.vsplit(r, [1,2])
print(r1, r1.shape)
print(r2, r2.shape)
print(r3, r3.shape)

[[1 9 8 2 3 1]] (1, 6)
[[2 7 2 6 0 9]] (1, 6)
[[2 6 6 2 7 7]
 [0 6 5 1 4 6]] (2, 6)


In [66]:
# 수평으로 3열을 자름
r1, r2 = np.hsplit(r, [3])
print(r1, r1.shape)
print(r2, r2.shape)

[[1 9 8]
 [2 7 2]
 [2 6 6]
 [0 6 5]] (4, 3)
[[2 3 1]
 [6 0 9]
 [2 7 7]
 [1 4 6]] (4, 3)


In [67]:
# 수평으로 2열과 4열을 자름
r1, r2, r3 = np.hsplit(r, [2,4]) # 2 번 잘라서 3개의 데이터로 나온 것
print(r1)
print(r2)
print(r3)

[[1 9]
 [2 7]
 [2 6]
 [0 6]]
[[8 2]
 [2 6]
 [6 2]
 [5 1]]
[[3 1]
 [0 9]
 [7 7]
 [4 6]]


### sort

In [68]:
r1 = np.random.randint(10, size=(3,3))
print(r1, r1.shape)

[[0 6 5]
 [1 2 1]
 [5 4 0]] (3, 3)


In [87]:
# 가로로 sorting
r1.sort(axis=-1) # axis -1과 1은 같은 동작을 한다
r1, r1.shape

(array([[0, 1, 2],
        [0, 4, 5],
        [1, 5, 6]]), (3, 3))

In [90]:
# 세로로 sorting
r1.sort() 
r1

array([[0, 1, 2],
       [0, 4, 5],
       [1, 5, 6]])

### 문제

- 1~9까지의 숫자가 들어가는 3*3 행렬을 만드세요
- 만든 행렬을 무작위로 섞으세요

In [71]:
result = np.arange(1,10);
result = np.reshape(result, (3,3))

In [72]:
np.random.shuffle(result)
result

array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [73]:
result.T

array([[7, 1, 4],
       [8, 2, 5],
       [9, 3, 6]])

In [74]:
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [75]:
np.r_[np.array([1,2,3]), np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])